6-module done
js-tasks-ru/jsbasic-20220901_ivankurt96 pull request #6
Opened 2022-09-29 15:57 UTC by IvanKurtts

2022-09-29 15:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-10-01 12:25 UTC, SinimaWath requested changes

2022-10-01 12:25 UTC, SinimaWath commented on 6-module/2-task/index.js
> +      event.target.closest(".card").dispatchEvent(new CustomEvent("product-add", {
А зачем так сложно?

у тебя же есть ссылка на card:
`elem.dispatchEvent(new CustomEvent(...))`

2022-10-01 12:25 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    }
Большие функции зачастую сложно читать, давай разбивать, хотябы по обработчиком событий:
```
arrowRight.addEventListener( "click", this.onArrowRightClick);
arrowLeft.addEventListener( "click", this.onArrowLeftClick);


button.addEventListener('click', this.onButtonClick)

```

2022-10-04 19:30 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-10-05 08:25 UTC, SinimaWath approved these changes

2022-10-05 08:26 UTC, merged